from module.transaction import transaction
import csv
class CSVReader:
    def __init__(self,filename,transactions):
        if len(transactions) == 0: self.transactionsEmpty = True
        else : self.transactionsEmpty = False
        self.filename = filename
        self.transactions = transactions
        self.checkFile()
    def checkFile(self):
        with open(self.filename, "r", encoding='ISO-8859-1') as file:
            csvreader = csv.reader(file)
            words = str(list(csvreader)[0]).split(";")
            file.close()
        if len(words) == 6: self.reread()
        elif len(words) == 17: self.read()
        else : print(len(words))

    #
    #section Read
    #
    #read from the sparkassen file
    def read(self):
        with open(self.filename, "r", encoding='ISO-8859-1') as file:
            csvreader = csv.reader(file)
            for row in csvreader:
                if self.transactionsEmpty:
                    self.transactions.append(transaction(self.extractProperties(str(row))))
                else:
                    tr = transaction(self.extractProperties(str(row)))
                    contained = False
                    for tr2 in self.transactions:
                        if tr2.equals(tr):contained = True
                    if not contained: self.transactions.append(tr)

    def extractProperties(self, row):
        words = self.stringCutElements(row)
        account = words[0]
        if account == "Auftragskonto":
            categorie = "Kategorie:"
        else:
            categorie = ""
        if words[11] == "":
            reciever = "Unknown"
        else:
            reciever = words[11]
        date = words[1]
        use = words[4]
        amount = words[14]
        return [account, categorie, reciever, date, use, amount]

    # take the row and extract the words char by char
    # remove ",',[,]
    def stringCutElements(self, row):
        words = []
        word = ""
        if len(row) > 0:
            for i in range(0, len(row) - 1):
                char = row[i]
                if char == ";":
                    words.append(word)
                    word = ""
                elif char not in [" ", "\"", "\'", "[", "]"]:
                    word += char
            words.append(word)
        return words

    #
    #section ReRead
    #
    #reread a file generated by this programm
    def reread(self):
        with open(self.filename,"r",encoding="ISO-8859-1") as file:
            csvreader = csv.reader(file)
            for row in csvreader:
                if self.transactionsEmpty: self.transactions.append(transaction(self.rereadProperties( self.removeSigns(row))))
                else :
                    tr = transaction(self.rereadProperties(self.removeSigns(row)))
                    contained = False
                    for tr2 in self.transactions:
                        if tr2.equals(tr): contained = True
                    if not contained: self.transactions.append(tr)
        # remove " ' [ ]
    def removeSigns(self, s):
        sout = str(s).replace("\"", "").replace("\'", "").replace("[", "").replace("]", "").replace(" ", "")

        return sout
    def rereadProperties(self,row):
        words = row.split(";")
        account = words[0]
        if account == "Auftragskonto":
            categorie = "Kategorie:"
        else:
            categorie = words[1]
        if words[2] == "":
            reciever = "Unknown"
        else:
            reciever = words[2]
        date = words[3]
        use = words[4]
        amount = words[5]
        return [account, categorie, reciever, date, use, amount]
